### ISSUE TITLE
Errors with stripe validation

### ISSUE THREAD

**Issue by Fizzwizz1** [thirtybees/stripe#62] opened 2022-12-26 13:24 UTC
I seem to be experiencing errors in 2 places

I have Thirty Bees 1.4.0
My Stripe API is 2022-11-15.
I also have the Panda theme installed.

I have 2 issues that I can see. I'm in test mode and on test transaction stripe processes the transaction, however on return to the stripe validation module at mysite.com/module/stripe/validation?type=cc returns the error:

An error occurred:
No charges associated with payment

The second error is if I select 'Enable Stripe Checkout' in Stripe Checkout options. When I go to checkout, I get a server 500 error at page mysite.com/orders after ticking the terms and conditions box then clicking 'proceed to checkout'

I get this error
ThirtyBeesStripe\Stripe\Error\ApiConnection
You cannot use `line_items.amount`, `line_items.currency`, `line_items.name`, `line_items.description`, or `line_items.images` in this API version. Please use `line_items.price` or `line_items.price_data`. Please see https://stripe.com/docs/payments/checkout/migrating-prices for more information.
in file /home/customer/www/mysite.co.uk/public_html/modules/stripe/classes/GuzzleClient.php at line 237

**Comment by getdatakick** [comment] 2022-12-28 08:37
This module is not compatible with API 2022-11-15.

Closing as duplicate of #56

**Closed by getdatakick** 2022-12-28 08:37 UTC
