### ISSUE TITLE
P24 not showing up

### ISSUE THREAD

**Issue by snaperr33** [thirtybees/stripe#51] opened 2022-01-12 13:54 UTC
Hi, I have configured the module, but it does not show me P24. I have everything on. Is there anything else that needs to be configured on the stripe side? Now it is possible to pay by card only.

![p24v1](https://user-images.githubusercontent.com/56622753/149153201-4d1d8f7e-c908-4e3e-ac78-c40af64ccefb.png)
![p24v2](https://user-images.githubusercontent.com/56622753/149153203-dd8615a6-ae0d-4422-a41f-0ead64e41df5.png)
![p24v3](https://user-images.githubusercontent.com/56622753/149153206-30d9a5a0-c507-4d7f-b465-c2a10ac539ee.png)
![p24v4](https://user-images.githubusercontent.com/56622753/149153208-24983852-0c0d-4d6c-83bc-1e19bef8db2f.png)
![p24v5](https://user-images.githubusercontent.com/56622753/149153210-c31565b7-8a98-4284-ac6a-ac766320fb83.png)
![p24v6](https://user-images.githubusercontent.com/56622753/149153212-479dc138-093d-4695-ac96-71d8ee3ad153.png)

**Comment by snaperr33** [comment] 2022-01-12 16:36
none of these 4 things worked

**Comment by snaperr33** [comment] 2022-01-12 16:38
do I have to have PLN as default currency in stripe? because I have the default EUR, but I also have PLN marked as additional

**Comment by adamus007p** [comment] 2022-01-12 17:15
during check out you need to have PLN, please check in payments options PLN are enabled too.

check in BO> modules >payments > Currency restrictions 
if PLN and stripe is enabled

**Comment by snaperr33** [comment] 2022-01-12 17:34
I cant select 
![p24v7](https://user-images.githubusercontent.com/56622753/149191984-0a3aba5c-3260-4964-95a1-67b0df343b64.png)

**Comment by adamus007p** [comment] 2022-01-12 19:04
Is it a fresh install? You may uninstall and install again or try some older version.

**Comment by snaperr33** [comment] 2022-01-12 19:05
Yes, new store, but already fully configured. I reinstalled the module and nothing

**Comment by snaperr33** [comment] 2022-01-13 14:58
what could be the reason?

**Comment by getdatakick** [comment] 2022-01-14 08:16
This is possibly duplicate of issue #44. That issue is fixed, by not yet part of any release.

You can try to do the same fix manually, see commit efc7e60911b9806cabcfa31883468866f17a2222

**Comment by snaperr33** [comment] 2022-01-14 09:09
work, thx :)

**Closed** 2022-01-14 09:09 UTC
Labels: bug
